### ISSUE TITLE
Controller 관련 HttpMethod 관련

### ISSUE THREAD

**Issue by wyjax** [eurowondollaryen/sayho-memoizer#1]
https://github.com/eurowondollaryen/sayho-memoizer/blob/241c06a12451b4a719286768416c875605afff21/src/main/java/com/sayho/memoizer/controller/QuizController.java#L33-L50

@RequestMapping("/quiz/regist") 부분을 >> @PostMapping("/quiz")  로
@RequestMapping("/quiz/delete") 부분을 >> @DeleteMapping("/quiz")  로 변경한다면 
어떨까요?

**Comment by eurowondollaryen** [comment]
굿굿
